### ISSUE TITLE
好像有个问题 拍照后 没有返回裁剪后的图 

### ISSUE THREAD

**Issue by liudao01** [YancyYe/GalleryPick#14]
拍照后 没有返回裁剪后的图  返回的是原图

**Comment by linyongsheng** [comment]
![image](https://cloud.githubusercontent.com/assets/5644908/16366435/e7fdef76-3c49-11e6-9514-ede89c378a47.png)  `ImageSelectorActivity`中的`onCameraShot`实现有问题 你按照上面的方式注释部分代码试试看

**Comment by liudao01** [comment]
@linyongsheng 我是直接引用的 没有导入  我尝试下载导入打开 gradle 总是挂掉   后来用文件最后创建的时间来判定的.

**Comment by linyongsheng** [comment]
@liudao01 你应该也是使用as吧 下载这个项目后 你尝试修改gradle为跟你的主项目一致的配置 试试看

**Comment by liudao01** [comment]
@linyongsheng 好的 谢了
