### ISSUE TITLE
内存泄漏啊

### ISSUE THREAD

**Issue by BigTimo** [YancyYe/GalleryPick#16]

**Comment by saplf** [comment]
同上

```java
GalleryConfig galleryConfig = new GalleryConfig.Builder()
                .imageLoader(new GlideImageLoader())    // ImageLoader 加载框架（必填）
                .iHandlerCallBack(iHandlerCallBack)     // 监听接口（必填）
                .build();
```

我看了一下源码，由于 `iHandlerCallBack` 很大可能是(匿名)内部类，持有外部类(一般是 `Activity` 或 `Fragment` )的引用，而最终 `iHandlerCallBack` 会被 `GalleryConfig` 的单例持有，造成内存泄露。
楼主或许可以考虑提供一个释放 `iHandlerCallBack` 的方法。

**Comment by saplf** [comment]
同上

```java
GalleryConfig galleryConfig = new GalleryConfig.Builder()
                .imageLoader(new GlideImageLoader())    // ImageLoader 加载框架（必填）
                .iHandlerCallBack(iHandlerCallBack)     // 监听接口（必填）
                .build();
```

我看了一下源码，由于 `iHandlerCallBack` 很大可能是(匿名)内部类，持有外部类(一般是 `Activity` 或 `Fragment` )的引用，而最终 `iHandlerCallBack` 会被 `GalleryConfig` 的单例持有，造成内存泄露。
楼主或许可以考虑提供一个释放 `iHandlerCallBack` 的方法。

**Comment by YancyYe** [comment]
GalleryPick clearHandlerCallBack
