### ISSUE TITLE
使用provider同时依赖GalleryPick报Error:Execution failed for task ':app:processDebugManifest'. > Manifest merger failed with multiple errors, see logs

### ISSUE THREAD

**Issue by kk-hua** [YancyYe/GalleryPick#18]
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preBetaBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2501Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72501Library UP-TO-DATE
:app:prepareComAndroidSupportDesign2400Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72501Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCompat2501Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUi2501Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUtils2501Library UP-TO-DATE
:app:prepareComAndroidSupportSupportFragment2501Library UP-TO-DATE
:app:prepareComAndroidSupportSupportMediaCompat2501Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42501Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2501Library UP-TO-DATE
:app:prepareComBigkooSvprogresshud102Library UP-TO-DATE
:app:prepareComDaimajiaSwipelayoutLibrary120Library UP-TO-DATE
:app:prepareComGithubYancyYeGalleryPick117Library UP-TO-DATE
:app:prepareComJakewhartonButterknife810Library UP-TO-DATE
:app:prepareComTencentBuglyCrashreport_upgrade123Library UP-TO-DATE
:app:prepareComTencentBuglyNativecrashreport312Library UP-TO-DATE
:app:prepareComYalantisUcrop220Library UP-TO-DATE
:app:prepareComYancyImageselectorImageselector130Library UP-TO-DATE
:app:prepareComZhyPercentSupportExtends111Library UP-TO-DATE
:app:prepareDeHdodenhofCircleimageview210Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources
:app:processDebugManifest
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:16:5-81 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:16:5-81 duplicated with element declared at AndroidManifest.xml:11:5-81
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:24:5-76 Warning:
	Element uses-permission#android.permission.ACCESS_WIFI_STATE at AndroidManifest.xml:24:5-76 duplicated with element declared at AndroidManifest.xml:10:5-76
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:26:5-79 Warning:
	Element uses-permission#android.permission.ACCESS_NETWORK_STATE at AndroidManifest.xml:26:5-79 duplicated with element declared at AndroidManifest.xml:5:5-79
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:28:5-76 Warning:
	Element uses-permission#android.permission.CHANGE_WIFI_STATE at AndroidManifest.xml:28:5-76 duplicated with element declared at AndroidManifest.xml:9:5-76
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:32:5-81 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:32:5-81 duplicated with element declared at AndroidManifest.xml:16:5-81
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:34:5-84 Warning:
	Element uses-permission#android.permission.MOUNT_UNMOUNT_FILESYSTEMS at AndroidManifest.xml:34:5-84 duplicated with element declared at AndroidManifest.xml:15:5-84
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:37:5-75 Warning:
	Element uses-permission#android.permission.READ_PHONE_STATE at AndroidManifest.xml:37:5-75 duplicated with element declared at AndroidManifest.xml:30:5-75
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:38:5-79 Warning:
	Element uses-permission#android.permission.ACCESS_NETWORK_STATE at AndroidManifest.xml:38:5-79 duplicated with element declared at AndroidManifest.xml:26:5-79
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:39:5-76 Warning:
	Element uses-permission#android.permission.ACCESS_WIFI_STATE at AndroidManifest.xml:39:5-76 duplicated with element declared at AndroidManifest.xml:24:5-76
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:41:5-84 Warning:
	Element uses-permission#android.permission.MOUNT_UNMOUNT_FILESYSTEMS at AndroidManifest.xml:41:5-84 duplicated with element declared at AndroidManifest.xml:34:5-84
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:42:5-81 Warning:
	Element uses-permission#android.permission.WRITE_EXTERNAL_STORAGE at AndroidManifest.xml:42:5-81 duplicated with element declared at AndroidManifest.xml:32:5-81
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:47:5-75 Warning:
	Element uses-permission#android.permission.READ_PHONE_STATE at AndroidManifest.xml:47:5-75 duplicated with element declared at AndroidManifest.xml:37:5-75
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:48:5-76 Warning:
	Element uses-permission#android.permission.ACCESS_WIFI_STATE at AndroidManifest.xml:48:5-76 duplicated with element declared at AndroidManifest.xml:39:5-76
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:49:5-79 Warning:
	Element uses-permission#android.permission.ACCESS_NETWORK_STATE at AndroidManifest.xml:49:5-79 duplicated with element declared at AndroidManifest.xml:38:5-79
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:53:5-73 Warning:
	Element uses-permission#android.permission.WRITE_SETTINGS at AndroidManifest.xml:53:5-73 duplicated with element declared at AndroidManifest.xml:12:5-73
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:55:5-68 Warning:
	Element uses-permission#android.permission.WAKE_LOCK at AndroidManifest.xml:55:5-68 duplicated with element declared at AndroidManifest.xml:8:5-68
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:58:5-68 Warning:
	Element uses-permission#android.permission.READ_LOGS at AndroidManifest.xml:58:5-68 duplicated with element declared at AndroidManifest.xml:40:5-68
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:61:5-68 Warning:
	Element uses-permission#android.permission.BLUETOOTH at AndroidManifest.xml:61:5-68 duplicated with element declared at AndroidManifest.xml:13:5-68
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:244:13-64 Error:
	Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.sh_rw.shrenwei.fileProvider) from AndroidManifest.xml:244:13-64
	is also present at [com.github.YancyYe:GalleryPick:1.1.7] AndroidManifest.xml:21:13-69 value=(com.yancy.gallerypick.fileprovider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:242:9-250:20 to override.
D:\duke\RW_Android\SHRenWei\app\src\main\AndroidManifest.xml:249:17-55 Error:
	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/provider_paths) from AndroidManifest.xml:249:17-55
	is also present at [com.github.YancyYe:GalleryPick:1.1.7] AndroidManifest.xml:26:17-50 value=(@xml/filepaths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml:247:13-249:57 to override.
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
:app:processDebugManifest FAILED
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

**Comment by YancyYe** [comment]
已修复  请更新只最新版本。1.1.8
