### ISSUE TITLE
直接启用相机可以加进去不,然后通过你的回调拿到图片

### ISSUE THREAD

**Issue by vipheyue** [YancyYe/GalleryPick#2]
直接启用相机可以加进去不,然后通过你的回调拿到图片

**Comment by YancyYe** [comment]
可以。。 我将在下个小版本加入这个功能，

**Comment by vipheyue** [comment]
3Q 等着你的作品

发自我的 iPhone

**Comment by YancyYe** [comment]
已在1.0.4版本中添加此功能。请看readme中的使用方法。 谢谢建议。

**Comment by vipheyue** [comment]
真棒！

发自我的 iPhone

**Comment by vipheyue** [comment]
点击直接开启相机 按钮  然后按返回键  能不能不要跳到选图的相册 感觉很奇怪 谢谢

**Comment by YancyYe** [comment]
刚没仔细测试，发现一个小bug  会在下个小版本修复， 谢谢建议

**Comment by vipheyue** [comment]
恩,在线等...我准备用到公司的项目上

**Comment by vipheyue** [comment]
还有一个问题是 ...我点击打开相册 ,他直接把相机给我打开了

**Comment by YancyYe** [comment]
已修复bug ，谢谢反馈。

**Comment by vipheyue** [comment]
点击直接开启相机 按钮 然后按返回键 还是跳到了 选图的那儿....能不能就像调用系统相机一样....返回之后就不要眺图册了 或者把图册关闭

**Comment by vipheyue** [comment]
在线等,,哥们

**Comment by YancyYe** [comment]
请更新到1.1.1  试试问题还在吗？

**Comment by vipheyue** [comment]
完美解决!等我把公司项目做完了,再来贡献你这个项目
