### ISSUE TITLE
java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.yancy.gallerypickdemo/cache/20170321195426.jpg

### ISSUE THREAD

**Issue by sivan67** [YancyYe/GalleryPick#25]
没有外部存储的时候，调用FileProvider.getUriForFile()方法会报错

**Comment by YancyYe** [comment]
filepaths.xml 中添加 内部储存就行了。。   

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <paths>
        <external-path
            name="external"
            path="" />
        <files-path
            name="files"
            path="" />
        <cache-path
            name="cache"
            path="" />
    </paths>
</resources>
