### ISSUE TITLE
图片选择器图片出现偏移

### ISSUE THREAD

**Issue by itwang** [YancyYe/GalleryPick#7]
![qq 20160310143610](https://cloud.githubusercontent.com/assets/5361366/13661432/9d6d3916-e6cd-11e5-9bab-b534768a63d7.png)

图片出现了整体向右偏移和覆盖 点击能够看到背景

**Comment by itwang** [comment]
app编译环境是Android studio sdk是23.0.1

**Comment by YancyYe** [comment]
好的  马上修改

**Comment by YancyYe** [comment]
已经修改完成  谢谢反馈
